site_back_office:
    resource: "@SiteBackOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

site_front_office:
    resource: "@SiteFrontOfficeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
site_frontoffice:
    resource: "@SiteFrontOfficeBundle/Controller/"
    type:     annotation